# Open Library API Configuration
# This file contains non-sensitive settings for the Open Library API handler

# Base URL for the Open Library API
base_url: "https://openlibrary.org"

# Default parameters for search API
default_search_params:
  limit: 10  # Default number of search results to return

# Endpoints for different API functionalities
endpoints:
  works: "/works/{work_id}.json"  # Endpoint for retrieving book details by work ID
  authors: "/authors/{author_id}.json"  # Endpoint for retrieving author details by author ID
  search: "/search.json"  # Endpoint for searching books

# Timeout settings for API requests (in seconds)
timeout: 30  # Default timeout for API requests