# Configuration for BaconPlaceholderAPI
# This YAML file contains non-sensitive operational parameters for the API

# Dimensions for the placeholder image
default_dimensions:
  width: 800
  height: 600

# URL template for the API
url_template: "https://baconmockup.com/{width}/{height}"

# Response handling
response:
  success_message: "Bacon placeholder image saved successfully"
  error_message: "Request to {url} failed with status code: {status_code}"
