# Configuration for Nominatim API usage
api:
  base_url: "https://nominatim.openstreetmap.org"
  endpoints:
    search: "/search"
    reverse: "/reverse"
    lookup: "/lookup"
  default_params:
    format: "json"
  headers:
    User-Agent: "NominatimGeocoder"
  rate_limit: 1  # Max 1 request per second