# Configuration for the TextProcessor module
# This module interacts with the Exude API for text processing

api:
  base_url: "https://exude.herokuapp.com/api"
  endpoints:
    text_filter: "/exude"
    file_filter: "/exude-file"
    swear_detection: "/exude-swear"

settings:
  timeout: 30  # Timeout in seconds for API requests
  max_retries: 3  # Maximum number of retries for failed requests

logging:
  level: "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"  # Log format
