[tool.poetry]
name = "kling-agent-image"
version = "0.0.1"
authors = ["Zonghuan Wu"]
description = "An agent for generating images using Kling AI"
license = "MIT License"
homepage = "https://github.com/moxin-org/mofa"
documentation = "https://github.com/moxin-org/mofa/blob/main/README.md"
readme = "README.md"
packages = [{ include = "agent" }]

[tool.poetry.dependencies]
pyarrow = ">=5.0.0"
loguru = "*"

[tool.poetry.scripts]
kling-agent-image = "agent.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"