[project]
name = "videoprompt"
version = "0.0.1"
description = "videoprompt Agent for generating videoprompt"
authors = [{name = "Your Name", email = "your.email@example.com"}]
requires-python = ">=3.12"
dependencies = [
    "mofa-ai @ file:///root/mofa-euterpe/python",
    "requests>=2.31.0",
    "python-dotenv==1.0.1",
    "pydantic==2.10.6",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "videoprompt"
version = "0.0.1"
description = "videoprompt Agent for generating Tintin-style videoprompt"
authors = ["Your Name <your.email@example.com>"]
packages = [{include = "videoprompt"}]

[tool.poetry.dependencies]
python = "^3.12"
mofa-ai = { path = "/root/mofa-euterpe/python", develop = true }
requests = ">=2.31.0"
python-dotenv = "1.0.1"
pydantic = "2.10.6"

[tool.poetry.scripts]
videoprompt = "videoprompt.agent.main:main"