[tool.poetry]
name = "owl-agent"
version = "0.1.1"
authors = [
    "Cheng Chen",
]
description = "deep inquire"
license = "MIT License"
homepage = "https://github.com/moxin-org/mofa"
documentation = "https://github.com/mem0ai/mem0"
readme = "README.md"
packages = [{ include = "owl_agent" }]

[tool.poetry.dependencies]
pyarrow = ">= 5.0.0"
owl = { url = "git+https://github.com/camel-ai/owl.git" }


[tool.poetry.scripts]
owl-agent = "owl_agent.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

