# Configuration for PlacebearAPI
# This YAML file contains non-sensitive operational parameters for the PlacebearAPI

# Image dimensions (default values)
image:
  width: 800
  height: 600

# Output file settings
output:
  filename: bear_placeholder.jpg