# Configuration for RickAndMortyAPIHandler
# This file contains non-sensitive settings for the Rick and Morty API endpoints

rick_and_morty_api:
  # Base URL for the Rick and Morty API
  base_url: "https://rickandmortyapi.com/api"

  # Endpoints configuration
  endpoints:
    characters: "/character"
    locations: "/location"
    episodes: "/episode"

  # Request timeout in seconds (optional)
  timeout: 30