# StackExchangeAPI Configuration
# This file contains non-sensitive settings for the Stack Exchange API integration.

api:
  base_url: "https://api.stackexchange.com/2.3"
  default_params:
    site: "stackoverflow"
    order: "desc"
    sort: "activity"
    pagesize: 5
  user_filter: "!9_bDDxJY5"  # Custom filter for basic profile data
  search_params:
    accepted: "true"
    pagesize: 3