# Configuration for QuoteAnalyzer
# This file contains non-sensitive settings for the Quotable API integration

base_url: "https://api.quotable.io"
endpoints:
  random_quote: "/quotes/random"
  search_quotes: "/search/quotes"
  author_details: "/authors/slug/{slug}"

default_params:
  search_fields: "content"

# Example of additional configurations (adjust as needed)
request_timeout: 10  # Timeout in seconds for API requests
max_retries: 3       # Maximum number of retries for failed requests