[tool.poetry]
name = "autogen-group"
version = "0.1.1"
authors = [
    "ZongHuan Wu ",
    "Cheng Chen",
]
description = "A simple autogen-group template"
license = "MIT License"
homepage = "https://github.com/moxin-org/mofa"
documentation = "https://github.com/moxin-org/mofa/blob/main/README.md"
readme = "README.md"
packages = [{ include = "autogen_group" }]

[tool.poetry.dependencies]
pyarrow = ">= 5.0.0"
autogen-groupchat = "*"
autogen-ext = {extras = ["openai",'web-surfer'], version = "*"}




[tool.poetry.scripts]
autogen-group = "autogen_group.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"


