# JioSaavnMusicAgent Configuration
# This file contains non-sensitive settings for the JioSaavn API integration.

api:
  base_url: "https://saavn.dev/api"
  endpoints:
    search_songs: "/search/songs"
    song_details: "/songs/{song_id}"
    playlist: "/playlists/{playlist_id}"
  request_timeout: 30  # Timeout in seconds for API requests

logging:
  level: "INFO"  # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
