# Configuration for NameAnalysisAgent

# API Endpoints
api_endpoints:
  agify: "https://api.agify.io"
  genderize: "https://api.genderize.io"
  nationalize: "https://api.nationalize.io"

# Default parameters for API requests
default_params:
  name: ""

# Timeout settings for API requests (in seconds)
timeout: 10

# Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
logging_level: "INFO"