# Configuration for WaifuImageFetcher
# This YAML file contains non-sensitive settings for the WaifuImageFetcher module.

# API Endpoints
api_endpoints:
  single_image: "https://api.waifu.pics/sfw/"
  multiple_images: "https://api.waifu.pics/many/"

# Default settings for API requests
defaults:
  category: "waifu"  # Default category for image requests
  type: "sfw"        # Default type ("sfw" or "nsfw")
  exclude: []         # Default exclusion list for multiple images

# Request settings
request:
  timeout: 30         # Timeout in seconds for API requests