# Configuration for DadJokeFetcher
# This YAML file contains non-sensitive settings for the DadJokeFetcher module.

# API Endpoints
api_endpoints:
  random_joke: "https://icanhazdadjoke.com/"
  search_jokes: "https://icanhazdadjoke.com/search"
  slack_joke: "https://icanhazdadjoke.com/slack"

# Default Headers for API requests
default_headers:
  random_joke:
    Accept: "application/json"
    User-Agent: "Python Script (https://example.com/contact)"
  search_jokes:
    Accept: "application/json"
    User-Agent: "Python Script (https://example.com/contact)"
  slack_joke:
    User-Agent: "Python Slack Bot (https://example.com/contact)"

# Search Parameters (for search_jokes endpoint)
search_params:
  term: "chicken"  # Default search term
  limit: 3          # Default limit for search results