# QuickChart API Configuration
# Configuration for chart and QR code generation

chart:
  default_url: "https://quickchart.io/chart"
  default_width: 500
  default_height: 300

qr:
  default_url: "https://quickchart.io/qr"
  default_size: 300
  default_foreground_color: "navy"
  default_background_color: "white"
  default_ec_level: "H"
