agent:
  pyproject_prompt: |
    **C: Context**  
    We need to automate generation of Poetry-compatible Python packages that strictly follow:  
    1. User-provided naming conventions (`agent_name`/`module_name`)  
    2. Dependency autodetection from code analysis  
    3. MIT-licensed open source structure  
    
    **O: Objective**  
    Create a perfect `pyproject.toml` that:  
    - 100% preserves user's `agent_name` (hyphenated) and `module_name` (underscored)  
    - Automatically adds dependencies like `requests` for HTTP calls  
    - Contains REQUIRED Poetry scripts/config sections  
    
    **S: Style**  
    Technical precision with:  
    - TOML syntax validation  
    - Named parameter interpolation (`{agent_name}`, `module_name`)  
    - Dependency fingerprints (code pattern → package mapping)  
    
    **T: Tone**  
    Authoritative yet adaptable:  
    - Error codes for invalid inputs (400/401/402)  
    - Clear package structure enforcement  
    - Strict no-hallucination policy for names  
    
    **A: Audience**  
    Python developers needing:  
    - Poetry packaging automation  
    - Dependency management  
    - CI/CD-ready configurations  
    
    **R: Response Format**  
    ```toml
    # STRICT TEMPLATE - NO DEVIATIONS
    [tool.poetry]
    name = "{agent_name}"
    version = "0.1.0"
    description = "Auto-generated agent package"
    authors = [
        "Mofa Bot <mofa-bot@moxin.com>",
        "Technical Owner <eng@moxin.com>"
    ]
    packages = [{ include = "{module_name}" }] # ⟨⟨critical⟩⟩ MUST PRESERVE USER INPUT
    
    [tool.poetry.dependencies]
    python = ">=3.10"
    pyarrow = ">= 5.0.0"
    # ⟨⟨auto⟩⟩ Detected from code patterns:
    # requests.get → requests = "*"
    
    [tool.poetry.scripts]
    {agent_name} = "{module_name}.main:main" # ⟨⟨unmodified⟩⟩ EXACT USER VALUES
    
    [build-system]
    requires = ["poetry-core>=1.8.0"]
    build-backend = "poetry.core.masonry.api"
    ```
    
    **Validation Triggers**  
     If `packages` doesn't EXACTLY match user's `module_name` → 401 error  
     If scripts section alters naming conventions → Full regeneration  
     Must pass `tomlkit.parse()` validation  
    
    **Examples**
    agent_name: UniversityFinder
    module_name: find_universities
    ```toml
    [tool.poetry]
    name = "UniversityFinder"
    version = "0.1.0"
    description = "Auto-generated agent package"
    authors = [
        "AI Mofa Bot Generator <mofa-bot@moxin.com>",
    ]
    packages = [{ include = "find_universities" }]
    
    [tool.poetry.dependencies]
    python = ">=3.10"
    requests = "*"
    
    [tool.poetry.scripts]
    UniversityFinder = "find_universities.main:main"
    
    [build-system]
    requires = ["poetry-core>=1.8.0"]
    build-backend = "poetry.core.masonry.api"
    ```

  readme_prompt: | 
    **C: Context**
    Automate technical documentation generation requiring:
    1. Precise code functionality analysis  
    2. Visual workflow representation  
    3. Strict naming convention preservation
    
    **O: Objective**
    Generate `README.md` containing:
    - Concise feature summary 
    - Mermaid workflow diagrams 
    - Class/method structure visualization
    - Input/output specifications
    
    **S: Style**
    Developer-friendly documentation:
    - Alternating code blocks/text explanations
    - Flowchart-to-code path verification
    - Critical parameters highlighting
    
    
    **A: Audience**
    Maintainers needing:
    - Quick architecture understanding
    - I/O specification validation
    - Core logic localization
    
    **T: Task**
    - Create a readme with code description based on the context provided
    - If the code contains receive_parameter, it means that the parameter is accepted. If it contains MofaAgent, it means that this code is an agent based on the Mofa framework. If there is send_output, what is the output content of this agent? Based on the code description content
    - Check if there are more than 3 logics in the code. If so, create a mermaid-based graph.



    
    
