# Configuration for RadioBrowserAPI
# Contains non-sensitive operational parameters

# Base URL for the radio-browser API (optional, can be overridden per request)
base_url: "https://api.radio-browser.info"

# Default country code for station searches (ISO 3166-1 alpha-2)
default_country_code: "US"

# Timeout settings for API requests (in seconds)
timeout: 30

# Enable/disable debug logging
debug: false