name: euterpe-agent
version: 0.1.0
description: MoFA agent to generate videos using euterpe-creator
options:
  use_environment_variables: true
  environment_variables:
    - KLING_API_KEY
    - BEATOVEN_API_KEY
    - DIFY_API_KEY
    - DIFY_API_BASE
    - DIFY_APP_ID
inputs:
  - name: params
    description: JSON parameters for video generation
    required: true
outputs:
  - name: euterpe_result
    description: Result of video generation
