[project]
name = "image2video"
version = "0.0.1"
description = "A MoFA agent for generating videos from images and prompts"
authors = [
    { name = "Zonghuan Wu" }
]
license = { text = "MIT License" }
readme = "README.md"
dependencies = [
    "pyarrow>=5.0.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    # "euterpe",  # Uncomment and specify version if available
]
requires-python = ">=3.8"  # Specify Python version here, not in dependencies

[project.urls]
Homepage = "https://github.com/moxin-org/mofa"
Documentation = "https://github.com/moxin-org/mofa/blob/main/README.md"

[project.scripts]
image2video = "image2video.main:main"

[tool.poetry]
name = "image2video"
version = "0.0.1"
description = "A MoFA agent for generating videos from images and prompts"
authors = ["Zonghuan Wu"]
license = "MIT License"
readme = "README.md"
homepage = "https://github.com/moxin-org/mofa"
documentation = "https://github.com/moxin-org/mofa/blob/main/README.md"
packages = [{ include = "image2video" }]

[tool.poetry.dependencies]
python = "^3.8"
pyarrow = ">=5.0.0"
python-dotenv = "^1.0.0"
requests = "^2.31.0"
# euterpe = "*"  # Uncomment and specify version/path if available

[tool.poetry.scripts]
image2video = "image2video.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"