[tool.poetry]
name = "kling-agent-video"
version = "0.0.1"
authors = ["Zonghuan Wu"]
description = "An agent for generating videos using Kling AI"
license = "MIT License"
homepage = "https://github.com/moxin-org/mofa"
documentation = "https://github.com/moxin-org/mofa/blob/main/README.md"
readme = "README.md"
packages = [{ include = "agent_video" }]

[tool.poetry.dependencies]
python = "^3.9"
pyarrow = ">=5.0.0"
loguru = "*"
python-dotenv = "*"
pyyaml = "*"

[tool.poetry.scripts]
kling-agent-video = "agent_video.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"