[tool.poetry]
name = "freepublic-apis"
version = "0.0.1"
authors = [
    "Zonghuan Wu"
]
description = "A user new agent template"
license = "MIT License"
homepage = "https://github.com/moxin-org/mofa"
documentation = "https://github.com/moxin-org/mofa/blob/main/README.md"
readme = "README.md"
packages = [{ include = "freepublic-apis" }]

[tool.poetry.dependencies]
pyarrow = ">= 5.0.0"
selenium = "*"
webdriver_manager = "*"
crawl4ai = "*"
pandas = "*"

[tool.poetry.scripts]
freepublic-apis = "freepublic-apis.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

