# Configuration for TriviaQuestionFetcher
# This file contains non-sensitive operational parameters for the trivia question fetcher.

defaults:
  # Base URL for the Open Trivia Database API
  base_url: "https://opentdb.com"

  # Default parameters for fetching questions
  question_params:
    amount: 10  # Number of questions to fetch
    category: 9  # Default category ID (General Knowledge)
    difficulty: "easy"  # Difficulty level (easy, medium, hard)
    type: "multiple"  # Question type (multiple, boolean)

  # Endpoints for various API calls
  endpoints:
    questions: "/api.php"
    categories: "/api_category.php"
    global_counts: "/api_count_global.php"

  # Timeout settings for API requests (in seconds)
  timeout: 30