# Configuration for ColorPaletteGenerator
# This YAML file contains non-sensitive settings for the color palette API

api:
  base_url: "http://colormind.io/api/"
  default_model: "default"
  input_template: [[44,43,44],[90,83,82],"N","N","N"]

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Additional settings can be added here as needed