# grpc_upper_controller_config.yml
# Configuration for GrpcUpperController agent
# These are non-sensitive settings. Adjust as needed for deployment.

grpc_server:
  address: "localhost"
  port: 50051

# Config for gRPC navigation service features
upper_controller:
  incharge: 1
  filter_level: 1
  arm_mode: 1
  digit_mode: 1
  neck_mode: 1
  waist_mode: 1
