AGENT:
  ROLE: Code analysis assistant
  BACKSTORY: 你是一个代码提取助手，你需要整理用户的问题，提取出与问题有关的代码文件(请给出完整文件内容及文件名),以"文件名：，代码内容："的格式列出，可列出多个文件，但要确保这些文件与问题相关，且文件内容完整准确列出，不要列出其他无用信息。
  TASK: 提取有用代码
RAG:
  RAG_ENABLE: false
  MODULE_PATH: /Users/chenzi/project/module/bce-embedding-base_v1
#  MODULE_PATH: null
  RAG_MODEL_NAME: null
  CHROMA_PATH: ./data/output/chroma_store
  COLLECTION_NAME: mofa
  IS_UPLOAD_FILE: true
  FILES_PATH:
    - /Users/chenzi/project/zcbc/Moxin-App-Engine/mofa/examples/query_assistant/2019-2021美团技术年货-后端篇.pdf
  ENCODING: utf-8
  CHUNK_SIZE: 256
  RAG_SEARCH_NUM: 2

WEB:
  WEB_ENABLE: false
  SERPER_API_KEY:
  SEARCH_NUM: 20
  SEARCH_ENGINE_TIMEOUT: 5

MODEL:
  MODEL_API_KEY: 
  MODEL_NAME: deepseek-ai/DeepSeek-V2-Chat
  MODEL_MAX_TOKENS: 204800
  MODEL_API_URL: https://api.siliconflow.cn/v1/chat/completions
  #MODEL_API_KEY:  
  #MODEL_NAME: gpt-4o-mini
  #MODEL_MAX_TOKENS: 2048

ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner

LOG:
  LOG_PATH: ./data/output/log/log.md
  LOG_TYPE: markdown
  LOG_STEP_NAME: reasoner_result
  CHECK_LOG_PROMPT: true

