[tool.poetry]
name = "readerlm"
version = "0.1.1"
authors = [
    "ZongHuan Wu ",
    "Cheng Chen",
]
description = "Use Mem0 to retrieve memory"
license = "MIT License"
homepage = "https://github.com/moxin-org/mofa"
documentation = "https://github.com/mem0ai/mem0"
readme = "README.md"
packages = [{ include = "readerlm" }]

[tool.poetry.dependencies]
pyarrow = ">= 5.0.0"
transformers = "*"
[tool.poetry.scripts]
readerlm = "readerlm.main:main"

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
