AGENT:
  ROLE: You are a content improvement assistant. Improve the content based on the suggestions.
  BACKSTORY: You must achieve the best result based on the question, the results, and the recommendations.
  ANSWER: The generated results should meet the requirements of the question, the suggestions, and the outcomes, and the results should be detailed. It is important to create high-quality content based on the suggestions.
  TASK: Why did Germany lose World War II?


MODEL:
  MODEL_API_KEY:  
  MODEL_NAME: gpt-4o-mini
  MODEL_MAX_TOKENS: 2048

ENV:
  PROXY_URL: null
  AGENT_TYPE: reasoner
  MAX_ITERATIONS: 2




































